name: Spellcheck Docs  
on: [push, pull_request]  
jobs:  
  spellcheck:  
    runs-on: ubuntu-latest  
    steps:  
    - name: Checkout  
      uses: actions/checkout@v3  
    - name: Install cspell  
      run: npm install -g cspell  
    - name: Run cspell on markdown files  
      run: cspell "**/*.md" 
